"""Optimize new Figma PNG exports before shipping them (requires Pillow).

Usage: python3 scripts/optimize-assets.py <directory containing PNG/SVG exports>
Original exports are not included in the production bundle.
"""

import argparse
import hashlib
import json
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
DESTINATION = ROOT / 'src/assets'


def widths_for(name, original_width):
    if name.endswith('-card.png') or name in {
        'conversation-trump.png', 'summary-elon.png', 'summary-luna.png'
    }:
        widths = [224, 448]
    elif name.endswith('-hero.png'):
        widths = [400, 800, original_width]
    elif name.endswith('-bg.png'):
        widths = [640, 1280, original_width]
    elif name == 'onboarding-people.png':
        widths = [724, original_width]
    elif name == 'summary-duo.png':
        widths = [652, 1304]
    elif name == 'score-78.png':
        widths = [226, 452]
    elif name == 'conversation-waveform.png':
        widths = [279, 558]
    else:
        widths = [original_width]
    return sorted({min(width, original_width) for width in widths})


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path)
    args = parser.parse_args()
    if not args.source.is_dir() or not any(args.source.rglob('*.png')):
        parser.error('Provide a directory containing PNG exports.')
    DESTINATION.mkdir(parents=True, exist_ok=True)
    duplicates = {}
    manifest = ROOT / 'src/assets-manifest.json'
    previous = json.loads(manifest.read_text()) if manifest.exists() else {}
    images = previous.get('images', {})
    aliases = {}
    assets = previous.get('assets', {})
    total_input = total_output = 0
    for source in sorted(args.source.rglob('*')):
        if source.suffix not in {'.png', '.svg'}:
            continue
        name = source.relative_to(args.source).as_posix()
        # The previous design's portrait is no longer used.
        if name == 'lee-card.png':
            continue
        if source.suffix == '.svg':
            target = DESTINATION / name
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(source.read_bytes())
            assets[name] = name
            continue
        total_input += source.stat().st_size
        digest = hashlib.sha256(source.read_bytes()).hexdigest()
        if digest in duplicates:
            aliases[name.replace('.png', '.webp')] = duplicates[digest]
            continue
        image = Image.open(source)
        stem = name.removesuffix('.png')
        widths = widths_for(source.name, image.width)
        variants = []
        for width in widths:
            height = round(image.height * width / image.width)
            resized = image.resize((width, height), Image.Resampling.LANCZOS)
            filename = f'{stem}.webp' if width == widths[-1] else f'{stem}-{width}.webp'
            target = DESTINATION / filename
            target.parent.mkdir(parents=True, exist_ok=True)
            resized.save(target, 'WEBP', quality=90, method=6, exact=True,
                         lossless=source.name in {'score-78.png', 'conversation-waveform.png'})
            total_output += target.stat().st_size
            variants.append((filename, width, height))
        logical_name = f'{stem}.webp'
        duplicates[digest] = logical_name
        images[logical_name] = variants
        assets[logical_name] = variants[-1][0]
    for alias, canonical in aliases.items():
        assets[alias] = assets[canonical]

    manifest.write_text(json.dumps({'assets': assets, 'images': images}, ensure_ascii=False, indent=2) + '\n')

    files = sorted(set(assets.values()) | {v[0] for vs in images.values() for v in vs})
    identifiers = {filename: f'asset{index}' for index, filename in enumerate(files)}
    output = ['// Generated by scripts/optimize-assets.py. Vite adds content hashes to asset URLs.']
    output += [f"import {identifiers[name]} from './assets/{name}'" for name in files]
    output += ['', 'const assets: Record<string, string> = {']
    output += [f"  '{name}': {identifiers[target]}," for name, target in sorted(assets.items())]
    output += ['}', '', 'export const responsiveImages: Record<string, { srcSet: string; width: number; height: number }> = {']
    for name, variants in images.items():
        main_image, width, height = variants[-1]
        srcset = ', '.join(f'${{{identifiers[filename]}}} {w}w' for filename, w, _ in variants)
        output += [f'  [{identifiers[main_image]}]: {{ srcSet: `{srcset}`, width: {width}, height: {height} }},']
    output += ['}', '', 'export function asset(name: string): string {',
               '  const url = assets[name]',
               '  if (!url) throw new Error(`Unknown asset: ${name}`)',
               '  return url', '}', '',
               "export const devdayAsset = (name: string) => asset(`devday/${name}`)", '']
    (ROOT / 'src/assets.ts').write_text('\n'.join(output))
    print(f'PNG inputs: {total_input:,} bytes; responsive WebP total: {total_output:,} bytes')
    print(f'Reduction: {100 * (1 - total_output / total_input):.1f}% (including all resolutions)')


if __name__ == '__main__':
    main()
