// Generated by scripts/optimize-assets.py. Vite adds content hashes to asset URLs.
import asset0 from './assets/atrium-bg-1280.webp'
import asset1 from './assets/atrium-bg-640.webp'
import asset2 from './assets/atrium-bg.webp'
import asset3 from './assets/devday/arrow-forward.svg'
import asset4 from './assets/devday/conversation-bg-1280.webp'
import asset5 from './assets/devday/conversation-bg-640.webp'
import asset6 from './assets/devday/conversation-bg.webp'
import asset7 from './assets/devday/conversation-trump-224.webp'
import asset8 from './assets/devday/conversation-trump.webp'
import asset9 from './assets/devday/conversation-video.webp'
import asset10 from './assets/devday/conversation-waveform-279.webp'
import asset11 from './assets/devday/conversation-waveform.webp'
import asset12 from './assets/devday/emoji-objects.svg'
import asset13 from './assets/devday/feedback-good.svg'
import asset14 from './assets/devday/feedback-improve.svg'
import asset15 from './assets/devday/feedback-report.svg'
import asset16 from './assets/devday/graphic-eq.svg'
import asset17 from './assets/devday/hangup.svg'
import asset18 from './assets/devday/microphone.svg'
import asset19 from './assets/devday/quick-phrases.svg'
import asset20 from './assets/devday/refresh.svg'
import asset21 from './assets/devday/score-78-226.webp'
import asset22 from './assets/devday/score-78.webp'
import asset23 from './assets/devday/score-line-71.svg'
import asset24 from './assets/devday/score-line-76.svg'
import asset25 from './assets/devday/score-line-82.svg'
import asset26 from './assets/devday/score-line-83.svg'
import asset27 from './assets/devday/score-line-end.svg'
import asset28 from './assets/devday/sms.svg'
import asset29 from './assets/devday/speaker-alt.svg'
import asset30 from './assets/devday/speaker.svg'
import asset31 from './assets/devday/speech-tail.svg'
import asset32 from './assets/devday/summary-bg-1280.webp'
import asset33 from './assets/devday/summary-bg-640.webp'
import asset34 from './assets/devday/summary-bg.webp'
import asset35 from './assets/devday/summary-duo-652.webp'
import asset36 from './assets/devday/summary-duo.webp'
import asset37 from './assets/devday/summary-elon-224.webp'
import asset38 from './assets/devday/summary-elon.webp'
import asset39 from './assets/devday/summary-luna-224.webp'
import asset40 from './assets/devday/summary-luna.webp'
import asset41 from './assets/devday/tip-check.svg'
import asset42 from './assets/divider.svg'
import asset43 from './assets/donald-hero-400.webp'
import asset44 from './assets/donald-hero-800.webp'
import asset45 from './assets/donald-hero.webp'
import asset46 from './assets/dooly-hero-400.webp'
import asset47 from './assets/dooly-hero-800.webp'
import asset48 from './assets/dooly-hero.webp'
import asset49 from './assets/einstein-card-224.webp'
import asset50 from './assets/einstein-card.webp'
import asset51 from './assets/einstein-hero-400.webp'
import asset52 from './assets/einstein-hero-800.webp'
import asset53 from './assets/einstein-hero.webp'
import asset54 from './assets/elon-hero-400.webp'
import asset55 from './assets/elon-hero-800.webp'
import asset56 from './assets/elon-hero.webp'
import asset57 from './assets/elsa-hero-400.webp'
import asset58 from './assets/elsa-hero.webp'
import asset59 from './assets/luna-hero-400.webp'
import asset60 from './assets/luna-hero-800.webp'
import asset61 from './assets/luna-hero.webp'
import asset62 from './assets/obama-card-224.webp'
import asset63 from './assets/obama-card.webp'
import asset64 from './assets/obama-hero-400.webp'
import asset65 from './assets/obama-hero-800.webp'
import asset66 from './assets/obama-hero.webp'
import asset67 from './assets/onboarding-people-724.webp'
import asset68 from './assets/onboarding-people.webp'
import asset69 from './assets/selection-arrow.svg'
import asset70 from './assets/selection-chat.svg'
import asset71 from './assets/sol-card-224.webp'
import asset72 from './assets/sol-card.webp'
import asset73 from './assets/sol-hero-400.webp'
import asset74 from './assets/sol-hero-800.webp'
import asset75 from './assets/sol-hero.webp'

const assets: Record<string, string> = {
  'atrium-bg.webp': asset2,
  'devday/arrow-forward.svg': asset3,
  'devday/conversation-bg.webp': asset6,
  'devday/conversation-trump.webp': asset8,
  'devday/conversation-video.webp': asset9,
  'devday/conversation-waveform.webp': asset11,
  'devday/emoji-objects.svg': asset12,
  'devday/feedback-good.svg': asset13,
  'devday/feedback-improve.svg': asset14,
  'devday/feedback-report.svg': asset15,
  'devday/graphic-eq.svg': asset16,
  'devday/hangup.svg': asset17,
  'devday/microphone.svg': asset18,
  'devday/quick-phrases.svg': asset19,
  'devday/refresh.svg': asset20,
  'devday/score-78.webp': asset22,
  'devday/score-line-71.svg': asset23,
  'devday/score-line-76.svg': asset24,
  'devday/score-line-82.svg': asset25,
  'devday/score-line-83.svg': asset26,
  'devday/score-line-end.svg': asset27,
  'devday/sms.svg': asset28,
  'devday/speaker-alt.svg': asset29,
  'devday/speaker.svg': asset30,
  'devday/speech-tail.svg': asset31,
  'devday/summary-bg.webp': asset34,
  'devday/summary-duo.webp': asset36,
  'devday/summary-elon.webp': asset38,
  'devday/summary-luna.webp': asset40,
  'devday/tip-check.svg': asset41,
  'divider.svg': asset42,
  'donald-card.webp': asset8,
  'donald-hero.webp': asset45,
  'dooly-hero.webp': asset48,
  'einstein-card.webp': asset50,
  'einstein-hero.webp': asset53,
  'elon-card.webp': asset38,
  'elon-hero.webp': asset56,
  'elsa-hero.webp': asset58,
  'luna-card.webp': asset40,
  'luna-hero.webp': asset61,
  'obama-card.webp': asset63,
  'obama-hero.webp': asset66,
  'onboarding-people.webp': asset68,
  'selection-arrow.svg': asset69,
  'selection-chat.svg': asset70,
  'sol-card.webp': asset72,
  'sol-hero.webp': asset75,
}

export const responsiveImages: Record<string, { srcSet: string; width: number; height: number }> = {
  [asset2]: { srcSet: `${asset1} 640w, ${asset0} 1280w, ${asset2} 1672w`, width: 1672, height: 941 },
  [asset6]: { srcSet: `${asset5} 640w, ${asset4} 1280w, ${asset6} 1672w`, width: 1672, height: 941 },
  [asset8]: { srcSet: `${asset7} 224w, ${asset8} 448w`, width: 448, height: 444 },
  [asset9]: { srcSet: `${asset9} 678w`, width: 678, height: 452 },
  [asset11]: { srcSet: `${asset10} 279w, ${asset11} 558w`, width: 558, height: 187 },
  [asset22]: { srcSet: `${asset21} 226w, ${asset22} 452w`, width: 452, height: 452 },
  [asset34]: { srcSet: `${asset33} 640w, ${asset32} 1280w, ${asset34} 1672w`, width: 1672, height: 941 },
  [asset36]: { srcSet: `${asset35} 652w, ${asset36} 1304w`, width: 1304, height: 1044 },
  [asset38]: { srcSet: `${asset37} 224w, ${asset38} 448w`, width: 448, height: 444 },
  [asset40]: { srcSet: `${asset39} 224w, ${asset40} 448w`, width: 448, height: 444 },
  [asset45]: { srcSet: `${asset43} 400w, ${asset44} 800w, ${asset45} 1086w`, width: 1086, height: 1448 },
  [asset50]: { srcSet: `${asset49} 224w, ${asset50} 448w`, width: 448, height: 444 },
  [asset53]: { srcSet: `${asset51} 400w, ${asset52} 800w, ${asset53} 1024w`, width: 1024, height: 1536 },
  [asset56]: { srcSet: `${asset54} 400w, ${asset55} 800w, ${asset56} 1024w`, width: 1024, height: 1536 },
  [asset61]: { srcSet: `${asset59} 400w, ${asset60} 800w, ${asset61} 1024w`, width: 1024, height: 1536 },
  [asset63]: { srcSet: `${asset62} 224w, ${asset63} 448w`, width: 448, height: 448 },
  [asset66]: { srcSet: `${asset64} 400w, ${asset65} 800w, ${asset66} 1024w`, width: 1024, height: 1536 },
  [asset68]: { srcSet: `${asset67} 724w, ${asset68} 1448w`, width: 1448, height: 1086 },
  [asset72]: { srcSet: `${asset71} 224w, ${asset72} 448w`, width: 448, height: 444 },
  [asset75]: { srcSet: `${asset73} 400w, ${asset74} 800w, ${asset75} 1024w`, width: 1024, height: 1536 },
  [asset48]: { srcSet: `${asset46} 400w, ${asset47} 800w, ${asset48} 1444w`, width: 1444, height: 1089 },
  [asset58]: { srcSet: `${asset57} 400w, ${asset58} 627w`, width: 627, height: 1275 },
}

export function asset(name: string): string {
  const url = assets[name]
  if (!url) throw new Error(`Unknown asset: ${name}`)
  return url
}

export const devdayAsset = (name: string) => asset(`devday/${name}`)
